### ISSUE TITLE
Sometimes System.AccessViolationException on Windows 10

### ISSUE THREAD

**Issue by wearhere** [mixmaxhq/electron-promote-windows-tray-items#1]
Observed for multiple users under Windows 10:

```
Application: mixmax.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
  at Squirrel.ITrayNotify.SetPreference(Squirrel.NOTIFYITEM_Writable ByRef)
  at Squirrel.TrayStateChanger.PromoteTrayItems(System.String)
  at Startup+<Invoke>d__0.MoveNext()
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Startup+<Invoke>d__0, tgfmyvbn, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](<Invoke>d__0 ByRef)
  at Startup.Invoke(System.String)

Exception Info: System.Reflection.TargetInvocationException
  at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
  at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
  at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
  at EdgeCompiler+<>c__DisplayClass1.<CompileFunc>b__0(System.Object)
  at ClrFunc.Call(v8.Local<v8::Value>, v8.Local<v8::Value>, v8.Local<v8::Value>)
  at <Module>.clrFuncProxy(Nan.FunctionCallbackInfo<v8::Value>)
  at <Module>.Nan.imp.?A0x09be68f5.FunctionCallbackWrapper(v8.FunctionCallbackInfo<v8::Value>*)
```

**Comment by wearhere** [comment]
@paulcbetts have you seen this before? I don't know enough about Windows / Windows development to say why this might be failing for particular users or how to remedy.

Ideally we would fix the issue of course.

Failing that, we'd get the user to change his configuration—presumably it is something particular to him, since I can't repro and we haven't heard this from other users.

If the code could figure out when the error would occur, just having this module silently fail would be fine too. Unfortunately this exception doesn't seem to be able to be caught—the app just crashes on launch for this user, without them seeing a regular Electron uncaught-exception error dialog—or else I'd just wrap the main logic in a try-catch and call it a day.

**Comment by wearhere** [comment]
Ah shoot, I just tried on a Windows 10 PC as opposed to my Parallels VM and reproduced it there, so perhaps it does happen for all Windows 10 users. x_x

EDIT: Nope, analytics reveals that some Windows 10 users are just fine.

**Comment by anaisbetts** [comment]
If you can build a repro app it'd be easy to debug with WinDbg

**Comment by expandrive** [comment]
Was curious if anyone figured out what the root issue was on this? Any luck?

**Comment by jeffbargmann** [comment]
Just a guess, 32bit code running on 64bit system? I wouldn't expect an issue, but Microsoft may not have predicted WOW64 apps calling this private API. Possible something's getting dropped in the mix? Noticing it's a struct with IntPtrs being passed to SetPreference.

**Comment by anaisbetts** [comment]
@JBLatenight Nope, IntPtr is explicitly the only type that correctly resizes based on architecture

**Comment by expandrive** [comment]
I've got a replicable case on Windows 10 x64 using .net v4.5.1 - . If I call promote function at load it always crashes at setpreference, but if I call it at any other time in the lifecycle of the app SetPreference just never returns [but everything else seems to work]. I can build a full reproducible app if necessary, but can any verify this interface actually works on Windows 10 x64?
